### ISSUE TITLE
PetScrapbook sample project failing to launch scrapbook-page

### ISSUE THREAD

**Issue by lakhanpalv** [mikebranstein/NativeScriptInAction#1]
Hi Mike & Nick,

I was reviewing your book and got some errors while running some sample code for chapter 8, like "JS: Cannot find function or filter: calcAge" or some errors while initializing the observable object. So I thought to check your working example from Github for chapter 8, but this one is also giving me quite a few errors. and it's not even launching the scrapbook-page when I click continue button on homepage.

I am using windows machine and running Google Nexus Emulator with NativeScript Runtime version 3.0.0.

Thanks,
Vivek

**Comment by NickBranstein** [comment]
Thanks Vivek. NativeScript just recently updated to 3.0 and we're working through the process of getting all the code samples updated. I'll take a look at Chapter 8 (sounds like the Pet Scrapbook) and let you know when I get it updated.

**Comment by lakhanpalv** [comment]
Hi Nick,

I was able to get calcAge working. If i set function like this:
`scrapbook.set("calcAge", function(year, month, day){
        var date = new Date(year, month, day);
        var now = Date.now();
        var diff = Math.abs(now - date) / 1000 / 31536000;
        return diff.toFixed(1);
    });`
Same thing for other variables for observable, e.g. `scrapbook.set("genders", ["Female", "Male"]);` 

Thanks,
Vivek

**Comment by Spikey88** [comment]
Hi lakhanpalv,

How did you get it to work exactly? I have tried your version but still get NAN on the age.
